export const container: string
export const header: string
export const studentName: string
export const status: string
export const statusMessage: string
export const box: string
export const boxHeader: string
export const boxTitle: string
export const boxBody: string
export const boxBodySmall: string
export const mark: string
export const buttons: string
export const checkButton: string
