# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pipe: atlassian/aws-code-deploy:0.5.0
            variables:
              AWS_DEFAULT_REGION: 'ap-southeast-2'
              COMMAND: 'deploy'
              APPLICATION_NAME: 'teams-ui'
              DEPLOYMENT_GROUP: 'teams-ui-deployment-group'
              WAIT: 'true'
