export const box: string
export const boxTitle: string
export const boxBody: string
export const criteria: string
export const criteriaTitle: string
export const tables: string
export const checkTable: string
export const checkTableTitle: string
export const checkTableInput: string
