export const box: string
export const boxTitle: string
export const boxMessage: string
export const blocks: string
export const block: string
export const blockTitle: string
export const blockChooseTemplateSection: string
export const blockButtons: string
export const templateSelect: string
export const mb32: string
export const mb24: string
