export const box: string
export const boxHeader: string
export const boxTitle: string
export const boxToggler: string
export const boxTogglerWithLabel: string
export const boxMessage: string
export const boxBody: string
export const boxButtons: string
export const mark: string
export const markInput: string
