export const sideMenu: string
export const nav: string
export const menu: string
export const menuItem: string
export const menuLink: string
export const checkIcon: string
export const retakeIcon: string
export const dashboardIcon: string
export const addAdminIcon: string
